---
title: "Mexico Crime Relations"
subtitle: "Proposal"
author: 
  - name: "Isabel Howe"
    affiliations:
      - name: "College of Information Science, University of Arizona"
description: " The goal is to create an interactive visualizations to facilitate in better understanding crime patterns in Mexico. If time permits, I plan to aim a bit higher and produce and interactive dashboard. There is a great utility in creating such a dashboard in many fields. Creating an interactive dashboard is something I have never pushed myself to do, and so, while I may regret the extra work, I find it'll be a task with high future reward.I also think that an interactive dashboard, or an interactive visualization, is a favorable way to get the viewers interested in the data."
format:
  html:
    code-tools: true
    code-overflow: wrap
    code-line-numbers: true
    embed-resources: true
editor: visual
code-annotations: hover
execute:
  warning: false
jupyter: python3
---


## Intro 
  The reason for analysing crime patterns in Mexico has to do with my background. I grew up spending all of my summers in Mexico, including
attended kindergarten there. I experienced two very different worlds in Mexico; at times, I would stay in a small ranch town in the mountains and at times 
on the Pacific coast in a city known to hold a large tourist attraction. I did not live a sheltered life there, nor did I stay in the safer upper class 
neighborhoods. I felt very safe growing up there; however, it's common knowledge that Mexico is not the safest country. That is why, when searching through 
Kaggle's platform, 'An Extensive Compilation of Criminal Incidents in Mexico' piqued my interest.

## Weekly plan:

```{python}
#| label: load-pkgs
#| message: false
#| echo: false
import pandas as pd

# Sample data for the timeline
data = {
    'Timeframe': ['08-07 to 08-08', '08-10', '08-11 to 08-13', '08-14 to 08-17', '08-18 to 08-20'],
    'Task': ['Find sources on creating interactive visuals', 'Study the data to find interesting patterns', 'Begin working on visuals and planning work up', 'Create visuals and write work up', 'Create presentation and finalize website details']
}

# Create a DataFrame
timeline_df = pd.DataFrame(data)

# Display the timeline table
print(timeline_df)

```


## Dataset
Two datasets will be used for this project. The main dataset  is 'Mexican Crime Statistics:Comprehensive (2015-2023)' sourced from Mexico's official 
government website (https://www.gob.mx/sre/en). The dataset is a compilation of criminal incidents reported across Mexico, form the years 2015-2023. The 
criminology record will be highly useful in assessing whether the crime in Mexico is evenly widespread throughout the country or clustered in certain regions.
The dataset consists of criminal incidents reported across Mexico from the years 2015 to 2023, offering insight into crime patterns and trends throughout 
differnet regions in Mexico. Some columns of interest include: 'Entity' (state), 'type_of_crime', 'subtype_of_crime', and 'count'. The original dataset
consists of 332416 rows and 9 columns. To condense the dataset, I filtered out all rows with a count of 0, and reduced the scooop to the years 2020-2022. 
This will allow me to focus on the most recent crime patterns, as well as reduce the size of the dataset to make it more manageable. Also, the additional 
dataset that will be used to compare crime rates with cartel presence, was collected in 2020, so it makes sense to focus on that time period. dataset now
consitts of 9 columns and 66049 rows. 


The second dataset of interest is 'BACRIM2020_Nodes' sourced from Mexico's official governent branch Centro Geo. This dataset was put together by piecing 
national and local newspapers together, along with narco blogs. The dataset consists of 151 rows and 4 columns. I'm specifically interested in 'State' 
and 'Group' columns. I would like to investigate whether there is a present correlation between high crimerates and high cartel presence. 

Below are some quick visualizations of the datasets.

```{python}
#| label: load-dataset
#| message: false
#| echo: false

import matplotlib.pyplot as plt


# load dataset into dataframe
mexi_crimes = pd.read_csv('data/mexico_crime_filtered.csv')
cartels = pd.read_csv('data/BACRIM2020_Nodes.csv')


# print dataframe shapes
print('Mexico Crime Statists DF Shape:', mexi_crimes.shape)
print('Mexico Crime Statists DF Shape:', cartels.shape)

#creating column to represent number of crimes per state
crimes_per_state = mexi_crimes.groupby('entity')['count'].sum().reset_index()
crimes_per_state['entity'] =crimes_per_state['entity'].replace({'Yucat?n': 'Yucatan', 'Quer?taro': 'Queretaro', 'Michoac?n de Ocampo': 'Michoacan de Ocampo', 'Nuevo Le?n': 'Nuevo Leon', 'San Luis Potos?': 'San Luis Potosi'}) # correct punctuation in state names
crimes_per_state = crimes_per_state[(crimes_per_state['entity'] != 'Ciudad de M?xico') & (crimes_per_state['entity'] != 'M?xico')]# Exclude as they are not a state

plt.figure(figsize=(10, 6))
plt.barh(crimes_per_state['entity'], crimes_per_state['count'], color='darkgreen')
plt.xlabel('Number of Crimes')
plt.ylabel('State')
plt.title('Total Crimes per State in Mexico (2020-2022)')
plt.tight_layout()
plt.show()

```




## Questions

1: Is the crime in Mexico evenly distributed throughout the country or is it most abundant in certain states?

2: Does Cartel presence correlate to a presence of crimes in the area?


## Analysis plan

To answer question 1, a new vector will be created to sum up the columns per state in Mexico. This new vector will sum the amount of crimes per state, 
which will the magnitude of crime rates per state to be compared. I plan on making an interactive bar plot to visual the data, each bar representing 
a different state. When the user hoovers over each bar, more details will appear; such as, highest types of crime. This will create a nice visual of the crime 
distribution throughout the coutry. 

To answer question 2, crime per state in Mexico will be compared with cartel presence in each state. I would like to make a simple
interactive dashboard to aid with answering this question. My plan is to have a scatter plot based on crime rates and possible amount of known cartel presence in the area. 
The user would then be able to select different states to take part of the visual. Depedning on how noisy the graph looks, I may only include areas with the highest crime 
rates or areas with the most cartel presence. If time does not permit, my plan is to create an interactive scatter plot that gives more details when the user hoovers over
the bars, instead of the dashboard. 